### ISSUE TITLE
Can you update your up to date js filename without version number?

### ISSUE THREAD

**Issue by dannyxx001** [on-site/guards.js#27]
Hello, I'm an intern from cdnjs(https://github.com/cdnjs/cdnjs).
I want to send pull request to add your lib(https://github.com/cdnjs/cdnjs/issues/7109), but it can't contain version number in filename. And I find files in downloads. Would you please update your filename?
Best regards.

**Comment by nilbus** [comment]
For consistency on our [downloads page](http://guardsjs.com/downloads.html), I think we should continue with the version number in the filename. It's a good practice to include the version number, so it's obvious what you're getting. [jQuery's downloads page](https://jquery.com/download/) also follows this convention.

If cdnjs requires a version without the filename, that's fine, since its directory structure specifies the version. Please just rename the file as part of your transfer process or script.

Thanks for including us in cdnjs!

**Comment by smellsblue** [comment]
@nilbus I wouldn't change the downloads page and the links on there, but we could potentially create some hidden files that aren't actually listed on the downloads page, or something to that effect.

@dannyxx001 is there any particular documentation for cdnjs that describes the structure required?

**Comment by dannyxx001** [comment]
@smellsblue Sorry for late reponse. However, I thing PeterDaveHello had replied to you. And now, it's enough to put guards.js to cdnjs. Thanks for your assistance.
